### ISSUE TITLE
[Bug] Cannot overwrite TUN route-exclude-address

### ISSUE THREAD

**Issue by n-WN** [mihomo-party-org/mihomo-party#704]
### Verify steps

- [x] 我已在标题简短的描述了我所遇到的问题
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
- [x] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
- [x] 这是 GUI 程序的问题，而不是内核程序的问题
- [x] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [x] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

macOS 14.7.4

### 发生问题 mihomo-party 版本

1.7.3

### 描述

```yaml
tun:
  exclude-interface+:
    - Tailscale
    - Rustdesk
  +route-exclude-address: # Not effective
    - 100.64.0.0/10
    - fd7a:115c:a1e0::/48
    - 10.0.0.0/8
    - 223.5.5.5/32
    - 1.1.1.1/32

+rules:
  - PROCESS-NAME,tailscale,DIRECT
  - PROCESS-NAME,tailscaled,DIRECT
```

### 重现方式

As above
