### ISSUE TITLE
[Feature] proxy-providers的节点外部资源能否手动更新？

### ISSUE THREAD

**Issue by Canda15** [mihomo-party-org/mihomo-party#719]
### Verify steps

- [x] 我已在标题简短的描述了我所需的功能
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过，但未找到我所需的功能
- [x] 这是向 GUI 程序提出的功能请求，而不是内核程序
- [x] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

没找到手动更新在哪。尝试重启clash，刷新订阅。都不行。必须得等他时间到了才能更新。我搜索了一下有人说 interval: 0 ，就可以在刷新订阅的时候一并更新节点信息。但也不行。希望能提供一个按钮

**Comment by AnyWAT** [comment]
> interval: 0

（在用节点）订阅管理，三个点菜单，编辑信息

![Image](https://github.com/user-attachments/assets/ca7cb02c-7846-4fd1-8078-56b84019b3cc)

**Comment by AnyWAT** [comment]
>外部资源能否手动更新

>在刷新订阅的时候一并更新节点信息

二者是指同一件事？前者的“自动更新”旁边的刷新按钮就是手动更新，后者本来就是如此。

**Comment by Canda15** [comment]
> > interval: 0
> 
> 貌似默认值。（在用节点）订阅管理，三个点菜单，编辑信息
> 
> ![Image](https://github.com/user-attachments/assets/ca7cb02c-7846-4fd1-8078-56b84019b3cc)

没看懂你在说啥，我重新表述一下吧。
```
mode: Rule
log-level: info
ipv6: true
dns:
  enable: true
  ipv6: true
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
proxy-providers:
  nodes:
    type: http
    url: "http://sub/Node.yaml"
    interval: 3600
    proxy: DIRECT
    override:
      udp: true
      skip-cert-verify: true
proxy-groups:
  - name: 🚀 节点选择
    type: select
    use:
      - nodes
```
当主配置文件，引用外部节点订阅时，proxy-providers:不会手动刷新。意思就是在订阅管理里点击那个刷新按钮，主配置文件刷新了，但是`proxy-providers:`里的 `url: "http://sub/Node.yaml"` 这个节点信息并不会一起更新。

或者加入到外部资源里也行。这样就能手动刷新节点信息了 #716 这里有人提了
