### ISSUE TITLE
[Bug] UDP TCP 分流表现不一致

### ISSUE THREAD

**Issue by xuhaoyang** [mihomo-party-org/mihomo-party#805]
### Verify steps

- [x] 我已在标题简短的描述了我所遇到的问题
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
- [x] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
- [x] 这是 GUI 程序的问题，而不是内核程序的问题
- [x] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [x] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

MacOS14.4

### 发生问题 mihomo-party 版本

1.7.5

### 描述

TCP走了正确的RULE-SET Google，UDP的走的不对。
![Image](https://github.com/user-attachments/assets/234c68ee-b85c-4315-8ff6-18895609822e)

### 重现方式

```
rule-providers:
  Google:
    type: http
    behavior: classical
    path: ./custom_RuleSet/Google.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Google/Google.yaml
    interval: *time_update_rule

  ProxyGFWlist: 
    type: http
    behavior: classical
    format: text
    path: ./custom_RuleSet/ProxyGFWlist.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/ProxyGFWlist.list
    interval: *time_update_rule

rules:
# Google服务
- RULE-SET,YouTube,📹 油管视频
- RULE-SET,Gemini,💬 Google
- RULE-SET,Google,💬 Google
...
...
....
- RULE-SET,ProxyGFWlist,🚀 节点选择
- GEOIP,LAN,🎯 全球直连,no-resolve
- GEOIP,CN,🎯 全球直连
- MATCH,🐟 漏网之鱼
```

💬 Google 与 🚀 节点选择 设置完全不同的节点

开启tun，tun模式Mixed/System/gVisor，在chrome中，访问 https://aistudio.google.com/prompts/new_chat ，就能复现出，UDP走的是🚀 节点选择，TCP走的是💬 Google
